In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
dir_path = "../data"
f_app_train = os.path.join(dir_path, "application_train.csv")
f_app_test = os.path.join(dir_path, "application_test.csv")

app_train = pd.read_csv(f_app_train)
app_test = pd.read_csv(f_app_test)

### 檢視資料中各個欄位類型的數量

In [6]:
app_train.dtypes.value_counts()

float64    65
int64      41
object     16
dtype: int64

In [7]:
app_test.dtypes.value_counts()

float64    65
int64      40
object     16
dtype: int64

### 檢視資料中類別型欄位各自類別的數量

In [9]:
app_train.select_dtypes(include = ["object"],).apply(pd.Series.nunique, axis = 0)

NAME_CONTRACT_TYPE             2
CODE_GENDER                    3
FLAG_OWN_CAR                   2
FLAG_OWN_REALTY                2
NAME_TYPE_SUITE                7
NAME_INCOME_TYPE               8
NAME_EDUCATION_TYPE            5
NAME_FAMILY_STATUS             6
NAME_HOUSING_TYPE              6
OCCUPATION_TYPE               18
WEEKDAY_APPR_PROCESS_START     7
ORGANIZATION_TYPE             58
FONDKAPREMONT_MODE             4
HOUSETYPE_MODE                 3
WALLSMATERIAL_MODE             7
EMERGENCYSTATE_MODE            2
dtype: int64

## Label Encoding

有仔細閱讀參考資料的人可以發現，Label encoding 的表示方式會讓同一個欄位底下的類別之間有大小關係 (0<1<2<...)，所以在這裡我們只對有類別數量小於等於 2 的類別型欄位示範使用 Label encoding，但不表示這樣處理是最好的，一切取決於欄位本身的意義適合哪一種表示方法

In [10]:
from sklearn.preprocessing import LabelEncoder

In [16]:
# Create a label encoder object
le = LabelEncoder()
le_count = 0

# Iterate through the columns
for col in app_train:
    if app_train[col].dtype == 'object':
        # If 2 or fewer unique categories
        if len(list(app_train[col].unique())) <= 2:
            # Train on the training data
            le.fit(app_train[col])
            # Transform both training and testing data
            app_train[col] = le.transform(app_train[col])
            app_test[col] = le.transform(app_test[col])
            
            # Keep track of how many columns were label encoded
            le_count += 1
            
print('%d columns were label encoded.' % le_count)

3 columns were label encoded.

## On hot Encodinig

pandas 中的 one hot encoding 非常方便，一行程式碼就搞定

In [18]:
app_train = pd.get_dummies(app_train)
app_test = pd.get_dummies(app_test)

print(app_train['CODE_GENDER_F'].head())
print(app_train['CODE_GENDER_M'].head())
print(app_train['NAME_EDUCATION_TYPE_Academic degree'].head())

0    0
1    1
2    0
3    1
4    0
Name: CODE_GENDER_F, dtype: uint8
0    1
1    0
2    1
3    0
4    1
Name: CODE_GENDER_M, dtype: uint8
0    0
1    0
2    0
3    0
4    0
Name: NAME_EDUCATION_TYPE_Academic degree, dtype: uint8

## 作業

In [19]:
app_train = pd.read_csv(f_app_train)
sub_train = pd.DataFrame(app_train['WEEKDAY_APPR_PROCESS_START'])
print(sub_train.shape)
sub_train.head()

(307511, 1)

  WEEKDAY_APPR_PROCESS_START
0                  WEDNESDAY
1                     MONDAY
2                     MONDAY
3                  WEDNESDAY
4                   THURSDAY

In [26]:
sub_train.shape
sub_train.head()

,WEEKDAY_APPR_PROCESS_START_FRIDAY,WEEKDAY_APPR_PROCESS_START_MONDAY,WEEKDAY_APPR_PROCESS_START_SATURDAY,WEEKDAY_APPR_PROCESS_START_SUNDAY,WEEKDAY_APPR_PROCESS_START_THURSDAY,WEEKDAY_APPR_PROCESS_START_TUESDAY,WEEKDAY_APPR_PROCESS_START_WEDNESDAY
0,0,0,0,0,0,0,1
1,0,1,0,0,0,0,0
2,0,1,0,0,0,0,0
3,0,0,0,0,0,0,1
4,0,0,0,0,1,0,0

In [23]:
sub_train = pd.get_dummies(sub_train)
sub_train

,WEEKDAY_APPR_PROCESS_START_FRIDAY,WEEKDAY_APPR_PROCESS_START_MONDAY,WEEKDAY_APPR_PROCESS_START_SATURDAY,WEEKDAY_APPR_PROCESS_START_SUNDAY,WEEKDAY_APPR_PROCESS_START_THURSDAY,WEEKDAY_APPR_PROCESS_START_TUESDAY,WEEKDAY_APPR_PROCESS_START_WEDNESDAY
0,0,0,0,0,0,0,1
1,0,1,0,0,0,0,0
2,0,1,0,0,0,0,0
3,0,0,0,0,0,0,1
4,0,0,0,0,1,0,0
5,0,0,0,0,0,0,1
6,0,0,0,1,0,0,0
7,0,1,0,0,0,0,0
8,0,0,0,0,0,0,1
9,0,0,0,0,1,0,0
10,0,0,1,0,0,0,0
11,1,0,0,0,0,0,0
12,1,0,0,0,0,0,0
13,0,0,0,0,1,0,0
14,0,1,0,0,0,0,0
15,0,0,1,0,0,0,0
16,0,0,0,0,1,0,0
17,0,1,0,0,0,0,0
18,1,0,0,0,0,0,0
19,0,1,0,0,0,0,0
20,1,0,0,0,0,0,0
21,0,1,0,0,0,0,0
22,0,0,0,0,1,0,0
23,1,0,0,0,0,0,0
24,0,0,0,0,1,0,0
25,0,0,1,0,0,0,0
26,0,1,0,0,0,0,0
27,0,0,1,0,0,0,0
28,0,0,0,0,0,0,1
29,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...
307481,1,0,0,0,0,0,0
307482,0,0,0,0,1,0,0
307483,0,1,0,0,0,0,0
307484,0,1,0,0,0,0,0
307485,0,0,1,0,0,0,0
307486,0,0,1,0,0,0,0
307487,0,0,0,0,0,0,1
307488,0,0,0,0,0,0,1
307489,1,0,0,0,0,0,0
307490,0,0,1,0,0,0,0
307491,0,0,1,0,0,0,0
307492,1,0,0,0,0,0,0
307493,0,1,0,0,0,0,0
307494,0,1,0,0,0,0,0
307495,0,0,0,0,0,0,1
307496,0,0,0,0,1,0,0
307497,0,0,0,0,1,0,0
307498,0,1,0,0,0,0,0
307499,0,0,0,0,0,1,0
307500,1,0,0,0,0,0,0
307501,0,0,0,0,0,0,1
307502,0,1,0,0,0,0,0
307503,0,0,1,0,0,0,0
307504,0,0,0,0,0,0,1
307505,0,1,0,0,0,0,0
307506,0,0,0,0,1,0,0
307507,0,1,0,0,0,0,0
307508,0,0,0,0,1,0,0
307509,0,0,0,0,0,0,1
307510,0,0,0,0,1,0,0